plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.google.services)
    alias(libs.plugins.firebase.crashlytics)
}

android {
    namespace 'com.aetherquorion.cleansuperai'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.aetherquorion.cleansuperai"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.process
    implementation libs.androidx.recyclerview
    implementation libs.coil
    implementation libs.coil.video
    implementation "com.google.android.gms:play-services-ads:25.4.0"
    implementation "com.google.ads.mediation:facebook:6.21.0.4"
    implementation "com.google.ads.mediation:mintegral:17.1.61.1"
    implementation "com.google.ads.mediation:pangle:8.1.0.5.0"
    implementation "com.unity3d.ads:unity-ads:4.19.0"
    implementation "com.google.ads.mediation:unity:4.19.0.0"
    implementation "com.google.android.ump:user-messaging-platform:2.2.0"
    implementation "com.android.installreferrer:installreferrer:2.2"
    implementation "com.squareup.okhttp3:okhttp:4.11.0"
    implementation "com.tencent:mmkv:1.3.14"
    implementation "com.google.code.gson:gson:2.8.9"
    implementation "org.greenrobot:eventbus:3.3.1"
    implementation "com.blankj:utilcodex:1.31.1"
    implementation libs.firebase.analytics
    implementation libs.firebase.crashlytics
    implementation "com.google.firebase:firebase-messaging:23.1.2"
    implementation "com.appsflyer:af-android-sdk:6.17.5"
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}
